### ISSUE TITLE
Dind permission issue: mounting local script files as volumes doesn't work when running Kestra itself in Docker

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#47]
### Expected Behavior

I was trying to mount a local directory to be used as a Kestra storage:

```yml
  kestra:
    volumes:
      - /Users/anna/.kestra/storage:/app/storage
```
Then I added the etl_script.py to that folder

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/b75f4629-a9fe-4c17-8994-ac063ebd09e4)

Example flow:
```yml
id: pythonVolume
namespace: dev
tasks:
  - id: anyPythonScript
    type: io.kestra.plugin.scripts.python.Commands
    runner: DOCKER
    docker:
      image: ghcr.io/kestra-io/pydata:latest
      volumes:
        - /app/storage:/app
    commands:
      - python /app/etl_script.py
      # - python /app/storage/etl_script.py
```

### Actual Behaviour

```Java
Image pulled [ghcr.io/kestra-io/pydata:latest]
Status 500: Mounts denied: 
The path /app/storage is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: Mounts denied: 
The path /app/storage is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.

	at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:42)
	at io.kestra.plugin.scripts.exec.scripts.runners.DockerScriptRunner.run(DockerScriptRunner.java:116)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:123)
	at io.kestra.plugin.scripts.python.Commands.run(Commands.java:90)
	at io.kestra.plugin.scripts.python.Commands.run(Commands.java:20)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:635)
```

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/b3525cfe-e0bf-447a-a7d2-cdbc864021ee)

### Environment Information

- Kestra Version: develop-full image

**Comment by tchiotludo** [comment]
Do you have setup this [option](https://kestra.io/docs/administrator-guide/configuration/others#kestratasksscriptsdockervolume-enabled) to enabled mount?

**Comment by anna-geller** [comment]
yes I have that enabled

**Comment by brian-mulier-p** [comment]
As said on slack, dind still acts as if the docker container was launched through command on host. Meaning the left-hand-side path in volume spec from docker options has to point towards your host directory (you don't need to volume mount from your host to your kestra container, just enable the option as @tchiotludo said).
This works:
```
id: pythonVolume
namespace: dev
tasks:
  - id: anyPythonScript
    type: io.kestra.plugin.scripts.python.Commands
    runner: DOCKER
    docker:
      image: python
      volumes:
        - /home/brian/python-scripts:/app/python-scripts
    commands:
      - python /app/python-scripts/script.py
```

Please confirm it is working and close the issue if that's the case ty !

**Comment by anna-geller** [comment]
I confirm it works, thanks so much! I will add to the docs

```yaml
id: pythonVolume
namespace: dev
tasks:
  - id: anyPythonScript
    type: io.kestra.plugin.scripts.python.Commands
    runner: DOCKER
    docker:
      image: ghcr.io/kestra-io/pydata:latest
      volumes:
        - /Users/anna/gh/KESTRA_REPOS/scripts:/app
    commands:
      - python /app/etl/parametrized.py
```

with the paratrized.py being:

```python
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("--num", type=int, default=42, help="Enter an integer")

args = parser.parse_args()
result = args.num * 2
print(result)
```

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/9da13b32-d955-4c81-aa06-64215b039990)
